[project]
name = "sekairanking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astrbot>=4.7.4",
    "asyncio>=4.0.0",
    "playwright>=1.56.0",
]
